version: '3'
services:
  nginx-php:
    build: 
      context: ./
    restart: always
    ports:
    - "${NGINX_HTTP_HOST_PORT}:80"
    volumes:
    - ${SOURCE_DIR}:/opt/case
    extra_hosts:
    networks:
      mywebnet:
        ipv4_address: 192.168.0.1
    links:
    tty: true
    cap_add:
    - SYS_PTRACE
networks:
  mywebnet:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.0.0/16